# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: htsjdk-igb build pipline 

on:
  push:
    branches: [ "igb-*" ]
  pull_request:
    branches: [ "igb-*" ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 1.8
    - name: Execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle (Skipping tests..)
      run: ./gradlew build -x tests
